"""Generation of .zshrc.generated, symlink management, and backup logic."""

import datetime
import pathlib
import typing

import pydantic

from pauldot import profiles

GENERATED_ZSHRC_REL = "files/.zshrc.generated"


class ZshrcResult(pydantic.BaseModel):
    action: typing.Literal["created", "backup_replaced", "replaced", "no_op"]
    zshrc: pathlib.Path
    target: pathlib.Path
    backup: pathlib.Path | None = None


def expected_content(repo_path: pathlib.Path, profile: profiles.ResolvedProfile) -> str:
    """Return the content pauldot would write to .zshrc.generated, without writing it."""
    aliases = repo_path / "files" / "aliases.zsh"
    env_generated = repo_path / "files" / ".env.generated"

    lines = [
        "# Generated by pauldot. Do not edit directly.",
        "# Edit source files or run `pauldot alias add`.",
        "",
    ]
    for zshrc_file in profile.zshrc_files:
        lines.append(f"source {zshrc_file}")
    if aliases.exists():
        lines.append(f"source {aliases}")
    lines.append(f"[ -f {env_generated} ] && source {env_generated}")

    return "\n".join(lines) + "\n"


def generate_zshrc(repo_path: pathlib.Path, profile: profiles.ResolvedProfile) -> pathlib.Path:
    """Write ~/.pauldot/files/.zshrc.generated from the resolved profile.

    Sources profile zshrc files in order (parent first), then aliases.zsh, then .env.generated.
    Returns the path to the generated file.
    """
    generated = repo_path / GENERATED_ZSHRC_REL
    generated.parent.mkdir(parents=True, exist_ok=True)
    generated.write_text(expected_content(repo_path, profile))
    return generated


def apply_zshrc(home: pathlib.Path, target: pathlib.Path, dry_run: bool = False) -> ZshrcResult:
    """Symlink ~/.zshrc to target, backing up any existing regular file.

    If dry_run is True the filesystem is not modified; the result describes what would happen.
    Raises FileNotFoundError if the target does not exist.
    """
    link = home / ".zshrc"

    if not target.exists():
        raise FileNotFoundError(
            f"Target not found: {target}.\nRun `pauldot init <repo-url>` to initialise your dotfiles repo first."
        )

    if link.is_symlink():
        if link.resolve() == target.resolve():
            return ZshrcResult(action="no_op", zshrc=link, target=target)
        # Points elsewhere — replace it, no backup needed.
        if not dry_run:
            link.unlink()
            link.symlink_to(target)
        return ZshrcResult(action="replaced", zshrc=link, target=target)

    if link.exists():
        # Regular file — back it up before replacing.
        timestamp = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
        backup = link.parent / f".zshrc.bak.{timestamp}"
        if not dry_run:
            link.rename(backup)
            link.symlink_to(target)
        return ZshrcResult(action="backup_replaced", zshrc=link, target=target, backup=backup)

    # Nothing there — create the symlink.
    if not dry_run:
        link.symlink_to(target)
    return ZshrcResult(action="created", zshrc=link, target=target)
