"""Generation of ~/.zshrc as a plain file from concatenated source files."""

import datetime
import pathlib
import typing

import pydantic

from pauldot import profiles

PAULDOT_HEADER = "# Generated by pauldot."


class ZshrcResult(pydantic.BaseModel):
    action: typing.Literal["created", "written", "no_op", "backup_replaced"]
    zshrc: pathlib.Path
    backup: pathlib.Path | None = None


def expected_content(repo_path: pathlib.Path, profile: profiles.ResolvedProfile) -> str:
    """Return the full content pauldot would write to ~/.zshrc."""
    parts: list[str] = [
        PAULDOT_HEADER,
        "# Edit source files in ~/.pauldot/files/ — do not edit this file directly.",
        "# Run `pauldot absorb` if external tools have appended lines here.",
        "",
    ]

    for zshrc_file in profile.zshrc_files:
        parts.append(zshrc_file.read_text().rstrip())
        parts.append("")

    aliases = repo_path / "files" / "aliases.zsh"
    if aliases.exists():
        parts.append(aliases.read_text().rstrip())
        parts.append("")

    profile_aliases = repo_path / "files" / f"aliases.{profile.name}.zsh"
    if profile_aliases.exists():
        parts.append(profile_aliases.read_text().rstrip())
        parts.append("")

    if profile.env:
        parts.append("# Environment — set by active profile")
        for key, value in sorted(profile.env.items()):
            parts.append(f'export {key}="{value}"')
        parts.append("")

    return "\n".join(parts) + "\n"


def apply_zshrc(
    home: pathlib.Path,
    repo_path: pathlib.Path,
    profile: profiles.ResolvedProfile,
    dry_run: bool = False,
) -> ZshrcResult:
    """Write ~/.zshrc as a plain file from concatenated source files.

    Detects pauldot ownership via PAULDOT_HEADER. Backs up non-pauldot files.
    Removes a legacy symlink (old model) and replaces it with a plain file.
    If dry_run is True the filesystem is not modified; the result describes what would happen.
    """
    zshrc_path = home / ".zshrc"
    expected = expected_content(repo_path, profile)

    if zshrc_path.is_symlink() and not dry_run:
        # Migration: old pauldot model wrote a symlink. Remove it and write a plain file.
        zshrc_path.unlink()
        # Fall through to the "nothing there" case below.

    if not zshrc_path.is_symlink() and zshrc_path.exists():
        content = zshrc_path.read_text()
        if content.startswith(PAULDOT_HEADER):
            if content == expected:
                return ZshrcResult(action="no_op", zshrc=zshrc_path)
            if not dry_run:
                zshrc_path.write_text(expected)
            return ZshrcResult(action="written", zshrc=zshrc_path)
        # Not pauldot-owned — back it up before replacing.
        timestamp = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
        backup = zshrc_path.parent / f".zshrc.bak.{timestamp}"
        if not dry_run:
            zshrc_path.rename(backup)
            zshrc_path.write_text(expected)
        return ZshrcResult(action="backup_replaced", zshrc=zshrc_path, backup=backup)

    # Nothing there (or symlink was just removed) — create the file.
    if not dry_run:
        zshrc_path.write_text(expected)
    return ZshrcResult(action="created", zshrc=zshrc_path)
